name: Testing icx
# specify the events this workflow should run on
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:  
     - name: Setup Node.js environment
       run: |
         sudo apt install nodejs
         sudo apt install npm
     - name: Install Dependencies
       run: |
         npm install
         node tsc
     - name: run tests
       run: node test-run.js  

