name: Testing icx
# specify the events this workflow should run on
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:  
     - name: Setup Node
       uses: actions/setup-node@v1
       with:
        node-version: '10.x'
     - name: Install Dependencies
       uses: Jaid/action-npm-install@v1.2.4
     - name: Typescript compiler
       # You may pin to the exact commit or the version.
       # uses: iCrawl/action-tsc@c3f25c126c7805dbbbcbf6f1db0c3be6f5dac069
       uses: iCrawl/action-tsc@v1
     - name: run tests
       run: node test-run.js  

