name: Testing icx
# specify the events this workflow should run on
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:  
     - name: Setup Node.js environment
       uses: actions/setup-node@v2.3.0
       with:
        node-version: 16.5.0
     - name: Install Dependencies
       run: |
         npm install
         node tsc
     - name: run tests
       run: node test-run.js  

